### ISSUE TITLE
How does version control work on this policy

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/OpenDataPolicy#11]
I can see we are currently working up to Version 2.0 for this policy.

I'm wondering what happens next in terms of version control.

With other projects we have created e.g. 2.0.1, 2.0.2 to allow for minor amendments and updates.

How are bug fixes, typos to be handled - would that just be another commit in this repo? (If so how do I know that my version 2.0 is your version 2.0)

Are you going to tag this as a 2.0 release like: https://github.com/OpenDataServices/OpenDataPolicy/releases

**Comment by stevieflow** [comment]
@caprenter do we have any convention for this within other open data services co-operative projects (CoVE?)?

I understand this to mean IATI:

> With other projects we have created e.g. 2.0.1, 2.0.2 to allow for minor amendments and updates.

**Comment by caprenter** [comment]
I don't think this is similar to CoVE.

I don't think we have any other 'documents' ourselves that are public facing. (Anything similar on GitHub I think it is assumed that people will understand github commits)

**Comment by stevieflow** [comment]
Thanks @caprenter 

Im happy to accept this new version as version 2 - and any tweaks can be 2.01, etc

If / when we get a new / different version then we can go to version 3

The changes between the previous and new version are significant to warrant an integer upgrade, I think

**Comment by ekoner** [comment]
Looks like @stevieflow has  answered the question for now - closing this issue
