### ISSUE TITLE
Privacy - mention of Organisation

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/OpenDataPolicy#6]
https://github.com/OpenDataServices/OpenDataPolicy/blob/master/OpenDataPolicy.md#privacy

> We will always ensure our open data is free from identifiers that could be linked to an individual person or organisation.

organisation might not be quite correct here, as we do wish for unique identifiers to be included for formal entities

**Comment by timgdavies** [comment]
Agreed. And we want to avoid boiling privacy down to just identifiers.

I might think about a better best practice would be:

"We will ensure we have explicit consent to publish any information about named or identifiable individuals. We will conduct a privacy impact assessment when planning to publish data to ensure any privacy risks are mitigated through [anonymization](http://ukanon.net/), redaction or aggregation of data prior to publication."

**Comment by ekoner** [comment]
@stevieflow @timgdavies please review this section in the version2 brnach and close if it resolves this issue.

**Comment by stevieflow** [comment]
Thanks @ekoner 

I think the most relevant update is in https://github.com/OpenDataServices/OpenDataPolicy/blob/version2/OpenDataPolicy.md#principle-1 

> We will ensure our open data is free from information that can be used on it’s own or with other information to identify a living person, as outlined in the ICO code of practice.

+1

**Comment by timgdavies** [comment]
+1
