### ISSUE TITLE
License

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/OpenDataPolicy#7]
This repo is a fork of a repo https://github.com/MaccData/OpenDataPolicy that is licensed under Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)

As a derivative work, this should:
"Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use."

I also think that Macc/Someone/Steven might want to put a copyright notice on the original as well.

**Comment by ekoner** [comment]
> Open Data Policy version 2.0 by Open Data Services Co-operative Limited is licenced under a Creative Commons Attribution-ShareAlike 4.0 International License.
> 
> © 2015 Open Data Services Co-operative Limited
> 
> Contains text from the Macc Open Data Policy
> 
> Source: http://www.macc.org.uk/sites/macc.org.uk/files/Open%20Data%20Policy.pdf
> 
> Copyright (c) Macc - Released under the Creative Commons Attribution-ShareAlike 4.0 International License http://creativecommons.org/licenses/by-sa/4.0/

Appears at the end of the appendix and template - did you have some other form of attribution in mind?

**Comment by caprenter** [comment]
Ah - ok. Great. I was looking at the front pages of he GitHub repos - where the README.md files both say (only):
This policy is published under Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)

Those documents should be updated.

What you have quoted above is good - I would be stronger on the link with the original.

"It is a derivative work of the Macc Open Data Policy with substantial changes." (link to Changleog.md)

to be clearer on "indicate if changes were made."

**Comment by ekoner** [comment]
I've strengthened or added attribution to:
- policy template
- appendix
- readme

**Comment by caprenter** [comment]
Great stuff. I think that is much better. I'm happy to close this now. Re-open if you want to  for any reason.
