### ISSUE TITLE
Changelog could also point to diff

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/OpenDataPolicy#9]
This may or not be useful, but raising the question.

The changelog could also link to a git diff of changes. (Although I'm not sure that the diff is 100% useful - but it is a bit useful!) https://github.com/OpenDataServices/OpenDataPolicy/compare/master...OpenDataServices:version2

I'm thinking tracking changes via git was one of the reasons for putting this in GitHub?

**Comment by ekoner** [comment]
Agreed - I've added the link to changelog.md

If that looks right, please close.

Cheers :)

**Comment by caprenter** [comment]
I'm going to assign to Ben- as I don't think that link will persist - we may want to do this as a pull request which would then persist (I think).

**Comment by Bjwebb** [comment]
Yes, I'd recommend creating and linking to a pull request.

**Comment by caprenter** [comment]
Ok - I've altered the link to point to https://github.com/OpenDataServices/OpenDataPolicy/pull/10 instead
